/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QueueRouteImport } from './routes/queue'
import { Route as FeedsRouteImport } from './routes/feeds'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FeedsIndexRouteImport } from './routes/feeds.index'
import { Route as EmailsIndexRouteImport } from './routes/emails.index'
import { Route as EmailIndexRouteImport } from './routes/email.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as FeedsFeedIdRouteImport } from './routes/feeds.$feedId'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthGmailCallbackRouteImport } from './routes/auth.gmail-callback'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AdminTagsRouteImport } from './routes/admin.tags'
import { Route as AdminGmailRouteImport } from './routes/admin.gmail'
import { Route as AdminDeadLinksRouteImport } from './routes/admin.dead-links'

const QueueRoute = QueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedsRoute = FeedsRouteImport.update({
  id: '/feeds',
  path: '/feeds',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedsIndexRoute = FeedsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FeedsRoute,
} as any)
const EmailsIndexRoute = EmailsIndexRouteImport.update({
  id: '/emails/',
  path: '/emails/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailIndexRoute = EmailIndexRouteImport.update({
  id: '/email/',
  path: '/email/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const FeedsFeedIdRoute = FeedsFeedIdRouteImport.update({
  id: '/$feedId',
  path: '/$feedId',
  getParentRoute: () => FeedsRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGmailCallbackRoute = AuthGmailCallbackRouteImport.update({
  id: '/auth/gmail-callback',
  path: '/auth/gmail-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTagsRoute = AdminTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGmailRoute = AdminGmailRouteImport.update({
  id: '/gmail',
  path: '/gmail',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDeadLinksRoute = AdminDeadLinksRouteImport.update({
  id: '/dead-links',
  path: '/dead-links',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/feeds': typeof FeedsRouteWithChildren
  '/queue': typeof QueueRoute
  '/admin/dead-links': typeof AdminDeadLinksRoute
  '/admin/gmail': typeof AdminGmailRoute
  '/admin/tags': typeof AdminTagsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/gmail-callback': typeof AuthGmailCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/feeds/$feedId': typeof FeedsFeedIdRoute
  '/admin/': typeof AdminIndexRoute
  '/email/': typeof EmailIndexRoute
  '/emails/': typeof EmailsIndexRoute
  '/feeds/': typeof FeedsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/queue': typeof QueueRoute
  '/admin/dead-links': typeof AdminDeadLinksRoute
  '/admin/gmail': typeof AdminGmailRoute
  '/admin/tags': typeof AdminTagsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/gmail-callback': typeof AuthGmailCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/feeds/$feedId': typeof FeedsFeedIdRoute
  '/admin': typeof AdminIndexRoute
  '/email': typeof EmailIndexRoute
  '/emails': typeof EmailsIndexRoute
  '/feeds': typeof FeedsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/feeds': typeof FeedsRouteWithChildren
  '/queue': typeof QueueRoute
  '/admin/dead-links': typeof AdminDeadLinksRoute
  '/admin/gmail': typeof AdminGmailRoute
  '/admin/tags': typeof AdminTagsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/gmail-callback': typeof AuthGmailCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/feeds/$feedId': typeof FeedsFeedIdRoute
  '/admin/': typeof AdminIndexRoute
  '/email/': typeof EmailIndexRoute
  '/emails/': typeof EmailsIndexRoute
  '/feeds/': typeof FeedsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/feeds'
    | '/queue'
    | '/admin/dead-links'
    | '/admin/gmail'
    | '/admin/tags'
    | '/auth/callback'
    | '/auth/gmail-callback'
    | '/auth/login'
    | '/feeds/$feedId'
    | '/admin/'
    | '/email/'
    | '/emails/'
    | '/feeds/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/queue'
    | '/admin/dead-links'
    | '/admin/gmail'
    | '/admin/tags'
    | '/auth/callback'
    | '/auth/gmail-callback'
    | '/auth/login'
    | '/feeds/$feedId'
    | '/admin'
    | '/email'
    | '/emails'
    | '/feeds'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/feeds'
    | '/queue'
    | '/admin/dead-links'
    | '/admin/gmail'
    | '/admin/tags'
    | '/auth/callback'
    | '/auth/gmail-callback'
    | '/auth/login'
    | '/feeds/$feedId'
    | '/admin/'
    | '/email/'
    | '/emails/'
    | '/feeds/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  FeedsRoute: typeof FeedsRouteWithChildren
  QueueRoute: typeof QueueRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthGmailCallbackRoute: typeof AuthGmailCallbackRoute
  AuthLoginRoute: typeof AuthLoginRoute
  EmailIndexRoute: typeof EmailIndexRoute
  EmailsIndexRoute: typeof EmailsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/queue': {
      id: '/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof QueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feeds': {
      id: '/feeds'
      path: '/feeds'
      fullPath: '/feeds'
      preLoaderRoute: typeof FeedsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feeds/': {
      id: '/feeds/'
      path: '/'
      fullPath: '/feeds/'
      preLoaderRoute: typeof FeedsIndexRouteImport
      parentRoute: typeof FeedsRoute
    }
    '/emails/': {
      id: '/emails/'
      path: '/emails'
      fullPath: '/emails/'
      preLoaderRoute: typeof EmailsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/': {
      id: '/email/'
      path: '/email'
      fullPath: '/email/'
      preLoaderRoute: typeof EmailIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/feeds/$feedId': {
      id: '/feeds/$feedId'
      path: '/$feedId'
      fullPath: '/feeds/$feedId'
      preLoaderRoute: typeof FeedsFeedIdRouteImport
      parentRoute: typeof FeedsRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/gmail-callback': {
      id: '/auth/gmail-callback'
      path: '/auth/gmail-callback'
      fullPath: '/auth/gmail-callback'
      preLoaderRoute: typeof AuthGmailCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tags': {
      id: '/admin/tags'
      path: '/tags'
      fullPath: '/admin/tags'
      preLoaderRoute: typeof AdminTagsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gmail': {
      id: '/admin/gmail'
      path: '/gmail'
      fullPath: '/admin/gmail'
      preLoaderRoute: typeof AdminGmailRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dead-links': {
      id: '/admin/dead-links'
      path: '/dead-links'
      fullPath: '/admin/dead-links'
      preLoaderRoute: typeof AdminDeadLinksRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDeadLinksRoute: typeof AdminDeadLinksRoute
  AdminGmailRoute: typeof AdminGmailRoute
  AdminTagsRoute: typeof AdminTagsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDeadLinksRoute: AdminDeadLinksRoute,
  AdminGmailRoute: AdminGmailRoute,
  AdminTagsRoute: AdminTagsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface FeedsRouteChildren {
  FeedsFeedIdRoute: typeof FeedsFeedIdRoute
  FeedsIndexRoute: typeof FeedsIndexRoute
}

const FeedsRouteChildren: FeedsRouteChildren = {
  FeedsFeedIdRoute: FeedsFeedIdRoute,
  FeedsIndexRoute: FeedsIndexRoute,
}

const FeedsRouteWithChildren = FeedsRoute._addFileChildren(FeedsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  FeedsRoute: FeedsRouteWithChildren,
  QueueRoute: QueueRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthGmailCallbackRoute: AuthGmailCallbackRoute,
  AuthLoginRoute: AuthLoginRoute,
  EmailIndexRoute: EmailIndexRoute,
  EmailsIndexRoute: EmailsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
