# fly.toml app configuration file generated for schwankie-api on 2023-06-08T15:08:19-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "schwankie-api"
primary_region = "bos"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
