# fly.toml app configuration file generated for schwankie-solr on 2024-10-18T15:05:44-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'schwankie-solr'
primary_region = 'ewr'

[build]

[http_service]
  internal_port = 8983
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
